from pathlib import Path
from datetime import datetime
import shutil

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


def export_pdf(plan):
    required_keys = [
        "destination",
        "days",
        "estimated_cost",
        "itinerary"
    ]

    for key in required_keys:
        if key not in plan:
            print(f"PDF generation skipped. Missing key: {key}")
            return None

    output_dir = Path("app") / "generated_plans"
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    pdf_path = output_dir / f"{plan['destination']}_{timestamp}.pdf"

    pdf = SimpleDocTemplate(str(pdf_path))
    styles = getSampleStyleSheet()
    content = []

    content.append(Paragraph("AI Travel Planner", styles["Title"]))
    content.append(Spacer(1, 20))
    content.append(Paragraph(f"<b>Destination:</b> {plan['destination']}", styles["BodyText"]))
    content.append(Paragraph(f"<b>Trip Duration:</b> {plan['days']} Days", styles["BodyText"]))
    content.append(Paragraph(f"<b>Estimated Cost:</b> ₹{plan['estimated_cost']}", styles["BodyText"]))

    if "weather" in plan and plan["weather"]:
        content.append(Paragraph(f"<b>Current Weather:</b> {plan['weather']}", styles["BodyText"]))

    content.append(Spacer(1, 15))
    content.append(Paragraph("Travel Itinerary", styles["Heading2"]))
    content.append(Spacer(1, 10))

    itinerary_lines = plan["itinerary"].split("\n")
    for line in itinerary_lines:
        line = line.strip()
        if not line:
            continue
        if line.lower().startswith("day"):
            content.append(Spacer(1, 10))
            content.append(Paragraph(f"<b>{line}</b>", styles["Heading3"]))
        else:
            content.append(Paragraph(f"• {line}", styles["BodyText"]))

    content.append(Spacer(1, 20))
    content.append(Paragraph("Recommendations", styles["Heading2"]))
    content.append(Spacer(1, 10))

    if "recommendations" in plan:
        for rec in plan["recommendations"]:
            content.append(Paragraph(f"• {rec}", styles["BodyText"]))

    content.append(Spacer(1, 20))
    content.append(Paragraph("Generated by AI Travel Planner Agent", styles["Italic"]))

    pdf.build(content)

    latest_pdf_path = Path("travel_plan.pdf")
    shutil.copyfile(pdf_path, latest_pdf_path)

    print(f"PDF generated successfully: {pdf_path}")
    print(f"Latest plan updated: {latest_pdf_path}")
    return str(pdf_path)
